name: Release and Publish Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@glassc'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Get version from tag
        id: version
        run: |
          # Extract version from the git tag
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Version from tag: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            ## CSS Style Release ${{ steps.version.outputs.version }}

            This release contains the latest version of the personal style guide CSS files.

            ### Files included:
            - `styles.css` - Original CSS file with full formatting and comments
            - `styles.min.css` - Minified version for production use

            ### Changes:
            - Updated styles and components
            - Generated from commit ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Original CSS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./styles.css
          asset_name: styles.css
          asset_content_type: text/css

      - name: Upload Minified CSS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/styles.min.css
          asset_name: styles.min.css
          asset_content_type: text/css

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
